//#ifdef RECORDER_GOTCHA
#include <gotcha/gotcha.h>
#include "recorder.h"

/* define gotcha-specific state to use with our wrapper */
#define RECORDER_WRAPPEE_HANDLE_DEF(func) \
gotcha_wrappee_handle_t wrappee_handle_ ## func

#define RECORDER_WRAPPEE_HANDLE(func) wrappee_handle_ ## func

/* POSIX I/O */
RECORDER_WRAPPEE_HANDLE_DEF(creat);
RECORDER_WRAPPEE_HANDLE_DEF(creat64);
RECORDER_WRAPPEE_HANDLE_DEF(open);
RECORDER_WRAPPEE_HANDLE_DEF(open64);
RECORDER_WRAPPEE_HANDLE_DEF(close);
RECORDER_WRAPPEE_HANDLE_DEF(write);
RECORDER_WRAPPEE_HANDLE_DEF(read);
RECORDER_WRAPPEE_HANDLE_DEF(lseek);
RECORDER_WRAPPEE_HANDLE_DEF(lseek64);
RECORDER_WRAPPEE_HANDLE_DEF(pread);
RECORDER_WRAPPEE_HANDLE_DEF(pread64);
RECORDER_WRAPPEE_HANDLE_DEF(pwrite);
RECORDER_WRAPPEE_HANDLE_DEF(pwrite64);
RECORDER_WRAPPEE_HANDLE_DEF(readv);
RECORDER_WRAPPEE_HANDLE_DEF(writev);
RECORDER_WRAPPEE_HANDLE_DEF(mmap);
RECORDER_WRAPPEE_HANDLE_DEF(mmap64);
RECORDER_WRAPPEE_HANDLE_DEF(msync);
RECORDER_WRAPPEE_HANDLE_DEF(fopen);
RECORDER_WRAPPEE_HANDLE_DEF(fopen64);
RECORDER_WRAPPEE_HANDLE_DEF(fclose);
RECORDER_WRAPPEE_HANDLE_DEF(fread);
RECORDER_WRAPPEE_HANDLE_DEF(fwrite);
RECORDER_WRAPPEE_HANDLE_DEF(ftell);
RECORDER_WRAPPEE_HANDLE_DEF(fseek);
RECORDER_WRAPPEE_HANDLE_DEF(fsync);
RECORDER_WRAPPEE_HANDLE_DEF(fdatasync);
RECORDER_WRAPPEE_HANDLE_DEF(vfprintf);
RECORDER_WRAPPEE_HANDLE_DEF(__xstat);
RECORDER_WRAPPEE_HANDLE_DEF(__xstat64);
RECORDER_WRAPPEE_HANDLE_DEF(__lxstat);
RECORDER_WRAPPEE_HANDLE_DEF(__lxstat64);
RECORDER_WRAPPEE_HANDLE_DEF(__fxstat);
RECORDER_WRAPPEE_HANDLE_DEF(__fxstat64);
RECORDER_WRAPPEE_HANDLE_DEF(getcwd);
RECORDER_WRAPPEE_HANDLE_DEF(mkdir);
RECORDER_WRAPPEE_HANDLE_DEF(rmdir);
RECORDER_WRAPPEE_HANDLE_DEF(chdir);
RECORDER_WRAPPEE_HANDLE_DEF(link);
RECORDER_WRAPPEE_HANDLE_DEF(linkat);
RECORDER_WRAPPEE_HANDLE_DEF(unlink);
RECORDER_WRAPPEE_HANDLE_DEF(symlink);
RECORDER_WRAPPEE_HANDLE_DEF(symlinkat);
RECORDER_WRAPPEE_HANDLE_DEF(readlink);
RECORDER_WRAPPEE_HANDLE_DEF(readlinkat);
RECORDER_WRAPPEE_HANDLE_DEF(rename);
RECORDER_WRAPPEE_HANDLE_DEF(chmod);
RECORDER_WRAPPEE_HANDLE_DEF(chown);
RECORDER_WRAPPEE_HANDLE_DEF(lchown);
RECORDER_WRAPPEE_HANDLE_DEF(utime);
RECORDER_WRAPPEE_HANDLE_DEF(opendir);
RECORDER_WRAPPEE_HANDLE_DEF(readdir);
RECORDER_WRAPPEE_HANDLE_DEF(closedir);
RECORDER_WRAPPEE_HANDLE_DEF(rewinddir);
RECORDER_WRAPPEE_HANDLE_DEF(mknod);
RECORDER_WRAPPEE_HANDLE_DEF(mknodat);
RECORDER_WRAPPEE_HANDLE_DEF(fcntl);
RECORDER_WRAPPEE_HANDLE_DEF(dup);
RECORDER_WRAPPEE_HANDLE_DEF(dup2);
RECORDER_WRAPPEE_HANDLE_DEF(pipe);
RECORDER_WRAPPEE_HANDLE_DEF(mkfifo);
RECORDER_WRAPPEE_HANDLE_DEF(umask);
RECORDER_WRAPPEE_HANDLE_DEF(fdopen);
RECORDER_WRAPPEE_HANDLE_DEF(fileno);
RECORDER_WRAPPEE_HANDLE_DEF(access);
RECORDER_WRAPPEE_HANDLE_DEF(faccessat);
RECORDER_WRAPPEE_HANDLE_DEF(tmpfile);
RECORDER_WRAPPEE_HANDLE_DEF(remove);
RECORDER_WRAPPEE_HANDLE_DEF(truncate);
RECORDER_WRAPPEE_HANDLE_DEF(ftruncate);
RECORDER_WRAPPEE_HANDLE_DEF(fseeko);
RECORDER_WRAPPEE_HANDLE_DEF(ftello);

/* MPI Function Calls */
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_close);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_set_size);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_iread_at);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_iread);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_iread_shared);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_iwrite_at);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_iwrite);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_iwrite_shared);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_open);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_read_all_begin);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_read_all);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_read_at_all);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_read_at_all_begin);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_read_at);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_read);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_read_ordered_begin);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_read_ordered);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_read_shared);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_set_view);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_sync);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_write_all_begin);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_write_all);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_write_at_all_begin);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_write_at_all);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_write_at);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_write);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_write_ordered_begin);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_write_ordered);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_write_shared);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Finalize);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Finalized);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Init);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Init_thread);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Wtime);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Comm_rank);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Comm_size);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Get_processor_name);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Comm_set_errhandler);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Barrier);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Bcast);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Gather);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Gatherv);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Scatter);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Scatterv);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Allgather);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Allgatherv);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Alltoall);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Reduce);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Allreduce);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Reduce_scatter);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Scan);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Type_commit);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Type_contiguous);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Type_extent);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Type_free);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Type_hindexed);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Op_create);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Op_free);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Type_get_envelope);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Type_size);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Type_create_darray);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_get_size);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Cart_rank);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Cart_create);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Cart_get);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Cart_shift);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Wait);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Send);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Recv);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Sendrecv);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Isend);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Irecv);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Info_create);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Info_set);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Info_get);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Waitall);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Waitsome);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Waitany);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Ssend);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Comm_split);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Comm_dup);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Comm_create);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_seek);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_File_seek_shared);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Ibcast);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Test);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Testall);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Testsome);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Testany);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Ireduce);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Igather);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Iscatter);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Ialltoall);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Comm_free);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Cart_sub);
RECORDER_WRAPPEE_HANDLE_DEF(PMPI_Comm_split_type);

/* HDF5 Function Calls */
/* NOTE: using HDF5 1.8 version */
RECORDER_WRAPPEE_HANDLE_DEF(H5Fcreate);
RECORDER_WRAPPEE_HANDLE_DEF(H5Fopen);
RECORDER_WRAPPEE_HANDLE_DEF(H5Fclose);
RECORDER_WRAPPEE_HANDLE_DEF(H5Fflush);
RECORDER_WRAPPEE_HANDLE_DEF(H5Gclose);
RECORDER_WRAPPEE_HANDLE_DEF(H5Gcreate1);
RECORDER_WRAPPEE_HANDLE_DEF(H5Gcreate2);
RECORDER_WRAPPEE_HANDLE_DEF(H5Gget_objinfo);
RECORDER_WRAPPEE_HANDLE_DEF(H5Giterate);
RECORDER_WRAPPEE_HANDLE_DEF(H5Gopen1);
RECORDER_WRAPPEE_HANDLE_DEF(H5Gopen2);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dclose);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dcreate1);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dcreate2);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dget_create_plist);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dget_space);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dget_type);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dopen1);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dopen2);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dread);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dwrite);
RECORDER_WRAPPEE_HANDLE_DEF(H5Dset_extent);
RECORDER_WRAPPEE_HANDLE_DEF(H5Sclose);
RECORDER_WRAPPEE_HANDLE_DEF(H5Screate);
RECORDER_WRAPPEE_HANDLE_DEF(H5Screate_simple);
RECORDER_WRAPPEE_HANDLE_DEF(H5Sget_select_npoints);
RECORDER_WRAPPEE_HANDLE_DEF(H5Sget_simple_extent_dims);
RECORDER_WRAPPEE_HANDLE_DEF(H5Sget_simple_extent_npoints);
RECORDER_WRAPPEE_HANDLE_DEF(H5Sselect_elements);
RECORDER_WRAPPEE_HANDLE_DEF(H5Sselect_hyperslab);
RECORDER_WRAPPEE_HANDLE_DEF(H5Sselect_none);
RECORDER_WRAPPEE_HANDLE_DEF(H5Tclose);
RECORDER_WRAPPEE_HANDLE_DEF(H5Tcopy);
RECORDER_WRAPPEE_HANDLE_DEF(H5Tget_class);
RECORDER_WRAPPEE_HANDLE_DEF(H5Tget_size);
RECORDER_WRAPPEE_HANDLE_DEF(H5Tset_size);
RECORDER_WRAPPEE_HANDLE_DEF(H5Tcreate);
RECORDER_WRAPPEE_HANDLE_DEF(H5Tinsert);
RECORDER_WRAPPEE_HANDLE_DEF(H5Aclose);
RECORDER_WRAPPEE_HANDLE_DEF(H5Acreate1);
RECORDER_WRAPPEE_HANDLE_DEF(H5Acreate2);
RECORDER_WRAPPEE_HANDLE_DEF(H5Aget_name);
RECORDER_WRAPPEE_HANDLE_DEF(H5Aget_num_attrs);
RECORDER_WRAPPEE_HANDLE_DEF(H5Aget_space);
RECORDER_WRAPPEE_HANDLE_DEF(H5Aget_type);
RECORDER_WRAPPEE_HANDLE_DEF(H5Aopen);
RECORDER_WRAPPEE_HANDLE_DEF(H5Aopen_idx);
RECORDER_WRAPPEE_HANDLE_DEF(H5Aopen_name);
RECORDER_WRAPPEE_HANDLE_DEF(H5Aread);
RECORDER_WRAPPEE_HANDLE_DEF(H5Awrite);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pclose);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pcreate);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pget_chunk);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pget_mdc_config);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_alignment);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_chunk);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_dxpl_mpio);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_fapl_core);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_fapl_mpio);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_fapl_mpiposix);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_istore_k);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_mdc_config);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_meta_block_size);
RECORDER_WRAPPEE_HANDLE_DEF(H5Lexists);
RECORDER_WRAPPEE_HANDLE_DEF(H5Lget_val);
RECORDER_WRAPPEE_HANDLE_DEF(H5Literate);
RECORDER_WRAPPEE_HANDLE_DEF(H5Literate1);
RECORDER_WRAPPEE_HANDLE_DEF(H5Literate2);
RECORDER_WRAPPEE_HANDLE_DEF(H5Oclose);
RECORDER_WRAPPEE_HANDLE_DEF(H5Oget_info);
RECORDER_WRAPPEE_HANDLE_DEF(H5Oget_info_by_name);
RECORDER_WRAPPEE_HANDLE_DEF(H5Oopen);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_coll_metadata_write);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pget_coll_metadata_write);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pset_all_coll_metadata_ops);
RECORDER_WRAPPEE_HANDLE_DEF(H5Pget_all_coll_metadata_ops);

struct gotcha_binding_t recorder_wrappers[] = {
    /* POSIX I/O */
    { "creat", RECORDER_POSIX_DECL(creat), &RECORDER_WRAPPEE_HANDLE(creat) },
    { "creat64", RECORDER_POSIX_DECL(creat64), &RECORDER_WRAPPEE_HANDLE(creat64) },
    { "open", RECORDER_POSIX_DECL(open), &RECORDER_WRAPPEE_HANDLE(open) },
    { "open64", RECORDER_POSIX_DECL(open64), &RECORDER_WRAPPEE_HANDLE(open64) },
    { "close", RECORDER_POSIX_DECL(close), &RECORDER_WRAPPEE_HANDLE(close) },
    { "write", RECORDER_POSIX_DECL(write), &RECORDER_WRAPPEE_HANDLE(write) },
    { "read", RECORDER_POSIX_DECL(read), &RECORDER_WRAPPEE_HANDLE(read) },
    { "lseek", RECORDER_POSIX_DECL(lseek), &RECORDER_WRAPPEE_HANDLE(lseek) },
    { "lseek64", RECORDER_POSIX_DECL(lseek64), &RECORDER_WRAPPEE_HANDLE(lseek64) },
    { "pread", RECORDER_POSIX_DECL(pread), &RECORDER_WRAPPEE_HANDLE(pread) },
    { "pread64", RECORDER_POSIX_DECL(pread64), &RECORDER_WRAPPEE_HANDLE(pread64) },
    { "pwrite", RECORDER_POSIX_DECL(pwrite), &RECORDER_WRAPPEE_HANDLE(pwrite) },
    { "pwrite64", RECORDER_POSIX_DECL(pwrite64), &RECORDER_WRAPPEE_HANDLE(pwrite64) },
    { "readv", RECORDER_POSIX_DECL(readv), &RECORDER_WRAPPEE_HANDLE(readv) },
    { "writev", RECORDER_POSIX_DECL(writev), &RECORDER_WRAPPEE_HANDLE(writev) },
    { "mmap", RECORDER_POSIX_DECL(mmap), &RECORDER_WRAPPEE_HANDLE(mmap) },
    { "mmap64", RECORDER_POSIX_DECL(mmap64), &RECORDER_WRAPPEE_HANDLE(mmap64) },
    { "msync", RECORDER_POSIX_DECL(msync), &RECORDER_WRAPPEE_HANDLE(msync) },
    { "fopen", RECORDER_POSIX_DECL(fopen), &RECORDER_WRAPPEE_HANDLE(fopen) },
    { "fopen64", RECORDER_POSIX_DECL(fopen64), &RECORDER_WRAPPEE_HANDLE(fopen64) },
    { "fclose", RECORDER_POSIX_DECL(fclose), &RECORDER_WRAPPEE_HANDLE(fclose) },
    { "fread", RECORDER_POSIX_DECL(fread), &RECORDER_WRAPPEE_HANDLE(fread) },
    { "fwrite", RECORDER_POSIX_DECL(fwrite), &RECORDER_WRAPPEE_HANDLE(fwrite) },
    { "ftell", RECORDER_POSIX_DECL(ftell), &RECORDER_WRAPPEE_HANDLE(ftell) },
    { "fseek", RECORDER_POSIX_DECL(fseek), &RECORDER_WRAPPEE_HANDLE(fseek) },
    { "fsync", RECORDER_POSIX_DECL(fsync), &RECORDER_WRAPPEE_HANDLE(fsync) },
    { "fdatasync", RECORDER_POSIX_DECL(fdatasync), &RECORDER_WRAPPEE_HANDLE(fdatasync) },
    { "vfprintf", RECORDER_POSIX_DECL(vfprintf), &RECORDER_WRAPPEE_HANDLE(vfprintf) },
    { "__xstat", RECORDER_POSIX_DECL(__xstat), &RECORDER_WRAPPEE_HANDLE(__xstat) },
    { "__xstat64", RECORDER_POSIX_DECL(__xstat64), &RECORDER_WRAPPEE_HANDLE(__xstat64) },
    { "__lxstat", RECORDER_POSIX_DECL(__lxstat), &RECORDER_WRAPPEE_HANDLE(__lxstat) },
    { "__lxstat64", RECORDER_POSIX_DECL(__lxstat64), &RECORDER_WRAPPEE_HANDLE(__lxstat64) },
    { "__fxstat", RECORDER_POSIX_DECL(__fxstat), &RECORDER_WRAPPEE_HANDLE(__fxstat) },
    { "__fxstat64", RECORDER_POSIX_DECL(__fxstat64), &RECORDER_WRAPPEE_HANDLE(__fxstat64) },
    { "getcwd", RECORDER_POSIX_DECL(getcwd), &RECORDER_WRAPPEE_HANDLE(getcwd) },
    { "mkdir", RECORDER_POSIX_DECL(mkdir), &RECORDER_WRAPPEE_HANDLE(mkdir) },
    { "rmdir", RECORDER_POSIX_DECL(rmdir), &RECORDER_WRAPPEE_HANDLE(rmdir) },
    { "chdir", RECORDER_POSIX_DECL(chdir), &RECORDER_WRAPPEE_HANDLE(chdir) },
    { "link", RECORDER_POSIX_DECL(link), &RECORDER_WRAPPEE_HANDLE(link) },
    { "linkat", RECORDER_POSIX_DECL(linkat), &RECORDER_WRAPPEE_HANDLE(linkat) },
    { "unlink", RECORDER_POSIX_DECL(unlink), &RECORDER_WRAPPEE_HANDLE(unlink) },
    { "symlink", RECORDER_POSIX_DECL(symlink), &RECORDER_WRAPPEE_HANDLE(symlink) },
    { "symlinkat", RECORDER_POSIX_DECL(symlinkat), &RECORDER_WRAPPEE_HANDLE(symlinkat) },
    { "readlink", RECORDER_POSIX_DECL(readlink), &RECORDER_WRAPPEE_HANDLE(readlink) },
    { "readlinkat", RECORDER_POSIX_DECL(readlinkat), &RECORDER_WRAPPEE_HANDLE(readlinkat) },
    { "rename", RECORDER_POSIX_DECL(rename), &RECORDER_WRAPPEE_HANDLE(rename) },
    { "chmod", RECORDER_POSIX_DECL(chmod), &RECORDER_WRAPPEE_HANDLE(chmod) },
    { "chown", RECORDER_POSIX_DECL(chown), &RECORDER_WRAPPEE_HANDLE(chown) },
    { "lchown", RECORDER_POSIX_DECL(lchown), &RECORDER_WRAPPEE_HANDLE(lchown) },
    { "utime", RECORDER_POSIX_DECL(utime), &RECORDER_WRAPPEE_HANDLE(utime) },
    { "opendir", RECORDER_POSIX_DECL(opendir), &RECORDER_WRAPPEE_HANDLE(opendir) },
    { "readdir", RECORDER_POSIX_DECL(readdir), &RECORDER_WRAPPEE_HANDLE(readdir) },
    { "closedir", RECORDER_POSIX_DECL(closedir), &RECORDER_WRAPPEE_HANDLE(closedir) },
    { "rewinddir", RECORDER_POSIX_DECL(rewinddir), &RECORDER_WRAPPEE_HANDLE(rewinddir) },
    { "mknod", RECORDER_POSIX_DECL(mknod), &RECORDER_WRAPPEE_HANDLE(mknod) },
    { "mknodat", RECORDER_POSIX_DECL(mknodat), &RECORDER_WRAPPEE_HANDLE(mknodat) },
    { "fcntl", RECORDER_POSIX_DECL(fcntl), &RECORDER_WRAPPEE_HANDLE(fcntl) },
    { "dup", RECORDER_POSIX_DECL(dup), &RECORDER_WRAPPEE_HANDLE(dup) },
    { "dup2", RECORDER_POSIX_DECL(dup2), &RECORDER_WRAPPEE_HANDLE(dup2) },
    { "pipe", RECORDER_POSIX_DECL(pipe), &RECORDER_WRAPPEE_HANDLE(pipe) },
    { "mkfifo", RECORDER_POSIX_DECL(mkfifo), &RECORDER_WRAPPEE_HANDLE(mkfifo) },
    { "umask", RECORDER_POSIX_DECL(umask), &RECORDER_WRAPPEE_HANDLE(umask) },
    { "fdopen", RECORDER_POSIX_DECL(fdopen), &RECORDER_WRAPPEE_HANDLE(fdopen) },
    { "fileno", RECORDER_POSIX_DECL(fileno), &RECORDER_WRAPPEE_HANDLE(fileno) },
    { "access", RECORDER_POSIX_DECL(access), &RECORDER_WRAPPEE_HANDLE(access) },
    { "faccessat", RECORDER_POSIX_DECL(faccessat), &RECORDER_WRAPPEE_HANDLE(faccessat) },
    { "tmpfile", RECORDER_POSIX_DECL(tmpfile), &RECORDER_WRAPPEE_HANDLE(tmpfile) },
    { "remove", RECORDER_POSIX_DECL(remove), &RECORDER_WRAPPEE_HANDLE(remove) },
    { "truncate", RECORDER_POSIX_DECL(truncate), &RECORDER_WRAPPEE_HANDLE(truncate) },
    { "ftruncate", RECORDER_POSIX_DECL(ftruncate), &RECORDER_WRAPPEE_HANDLE(ftruncate) },
    { "fseeko", RECORDER_POSIX_DECL(fseeko), &RECORDER_WRAPPEE_HANDLE(fseeko) },
    { "ftello", RECORDER_POSIX_DECL(ftello), &RECORDER_WRAPPEE_HANDLE(ftello) },
    
    /* MPI Function Calls */
    { "PMPI_File_close", RECORDER_MPI_DECL(PMPI_File_close), &RECORDER_WRAPPEE_HANDLE(PMPI_File_close) },
    { "PMPI_File_set_size", RECORDER_MPI_DECL(PMPI_File_set_size), &RECORDER_WRAPPEE_HANDLE(PMPI_File_set_size) },
    { "PMPI_File_iread_at", RECORDER_MPI_DECL(PMPI_File_iread_at), &RECORDER_WRAPPEE_HANDLE(PMPI_File_iread_at) },
    { "PMPI_File_iread", RECORDER_MPI_DECL(PMPI_File_iread), &RECORDER_WRAPPEE_HANDLE(PMPI_File_iread) },
    { "PMPI_File_iread_shared", RECORDER_MPI_DECL(PMPI_File_iread_shared), &RECORDER_WRAPPEE_HANDLE(PMPI_File_iread_shared) },
    { "PMPI_File_iwrite_at", RECORDER_MPI_DECL(PMPI_File_iwrite_at), &RECORDER_WRAPPEE_HANDLE(PMPI_File_iwrite_at) },
    { "PMPI_File_iwrite", RECORDER_MPI_DECL(PMPI_File_iwrite), &RECORDER_WRAPPEE_HANDLE(PMPI_File_iwrite) },
    { "PMPI_File_iwrite_shared", RECORDER_MPI_DECL(PMPI_File_iwrite_shared), &RECORDER_WRAPPEE_HANDLE(PMPI_File_iwrite_shared) },
    { "PMPI_File_open", RECORDER_MPI_DECL(PMPI_File_open), &RECORDER_WRAPPEE_HANDLE(PMPI_File_open) },
    { "PMPI_File_read_all_begin", RECORDER_MPI_DECL(PMPI_File_read_all_begin), &RECORDER_WRAPPEE_HANDLE(PMPI_File_read_all_begin) },
    { "PMPI_File_read_all", RECORDER_MPI_DECL(PMPI_File_read_all), &RECORDER_WRAPPEE_HANDLE(PMPI_File_read_all) },
    { "PMPI_File_read_at_all", RECORDER_MPI_DECL(PMPI_File_read_at_all), &RECORDER_WRAPPEE_HANDLE(PMPI_File_read_at_all) },
    { "PMPI_File_read_at_all_begin", RECORDER_MPI_DECL(PMPI_File_read_at_all_begin), &RECORDER_WRAPPEE_HANDLE(PMPI_File_read_at_all_begin) },
    { "PMPI_File_read_at", RECORDER_MPI_DECL(PMPI_File_read_at), &RECORDER_WRAPPEE_HANDLE(PMPI_File_read_at) },
    { "PMPI_File_read", RECORDER_MPI_DECL(PMPI_File_read), &RECORDER_WRAPPEE_HANDLE(PMPI_File_read) },
    { "PMPI_File_read_ordered_begin", RECORDER_MPI_DECL(PMPI_File_read_ordered_begin), &RECORDER_WRAPPEE_HANDLE(PMPI_File_read_ordered_begin) },
    { "PMPI_File_read_ordered", RECORDER_MPI_DECL(PMPI_File_read_ordered), &RECORDER_WRAPPEE_HANDLE(PMPI_File_read_ordered) },
    { "PMPI_File_read_shared", RECORDER_MPI_DECL(PMPI_File_read_shared), &RECORDER_WRAPPEE_HANDLE(PMPI_File_read_shared) },
    { "PMPI_File_set_view", RECORDER_MPI_DECL(PMPI_File_set_view), &RECORDER_WRAPPEE_HANDLE(PMPI_File_set_view) },
    { "PMPI_File_sync", RECORDER_MPI_DECL(PMPI_File_sync), &RECORDER_WRAPPEE_HANDLE(PMPI_File_sync) },
    { "PMPI_File_write_all_begin", RECORDER_MPI_DECL(PMPI_File_write_all_begin), &RECORDER_WRAPPEE_HANDLE(PMPI_File_write_all_begin) },
    { "PMPI_File_write_all", RECORDER_MPI_DECL(PMPI_File_write_all), &RECORDER_WRAPPEE_HANDLE(PMPI_File_write_all) },
    { "PMPI_File_write_at_all_begin", RECORDER_MPI_DECL(PMPI_File_write_at_all_begin), &RECORDER_WRAPPEE_HANDLE(PMPI_File_write_at_all_begin) },
    { "PMPI_File_write_at_all", RECORDER_MPI_DECL(PMPI_File_write_at_all), &RECORDER_WRAPPEE_HANDLE(PMPI_File_write_at_all) },
    { "PMPI_File_write_at", RECORDER_MPI_DECL(PMPI_File_write_at), &RECORDER_WRAPPEE_HANDLE(PMPI_File_write_at) },
    { "PMPI_File_write", RECORDER_MPI_DECL(PMPI_File_write), &RECORDER_WRAPPEE_HANDLE(PMPI_File_write) },
    { "PMPI_File_write_ordered_begin", RECORDER_MPI_DECL(PMPI_File_write_ordered_begin), &RECORDER_WRAPPEE_HANDLE(PMPI_File_write_ordered_begin) },
    { "PMPI_File_write_ordered", RECORDER_MPI_DECL(PMPI_File_write_ordered), &RECORDER_WRAPPEE_HANDLE(PMPI_File_write_ordered) },
    { "PMPI_File_write_shared", RECORDER_MPI_DECL(PMPI_File_write_shared), &RECORDER_WRAPPEE_HANDLE(PMPI_File_write_shared) },
    { "PMPI_Finalize", RECORDER_MPI_DECL(PMPI_Finalize), &RECORDER_WRAPPEE_HANDLE(PMPI_Finalize) },
    { "PMPI_Finalized", RECORDER_MPI_DECL(PMPI_Finalized), &RECORDER_WRAPPEE_HANDLE(PMPI_Finalized) },
    { "PMPI_Init", RECORDER_MPI_DECL(PMPI_Init), &RECORDER_WRAPPEE_HANDLE(PMPI_Init) },
    { "PMPI_Init_thread", RECORDER_MPI_DECL(PMPI_Init_thread), &RECORDER_WRAPPEE_HANDLE(PMPI_Init_thread) },
    { "PMPI_Wtime", RECORDER_MPI_DECL(PMPI_Wtime), &RECORDER_WRAPPEE_HANDLE(PMPI_Wtime) },
    { "PMPI_Comm_rank", RECORDER_MPI_DECL(PMPI_Comm_rank), &RECORDER_WRAPPEE_HANDLE(PMPI_Comm_rank) },
    { "PMPI_Comm_size", RECORDER_MPI_DECL(PMPI_Comm_size), &RECORDER_WRAPPEE_HANDLE(PMPI_Comm_size) },
    { "PMPI_Get_processor_name", RECORDER_MPI_DECL(PMPI_Get_processor_name), &RECORDER_WRAPPEE_HANDLE(PMPI_Get_processor_name) },
    { "PMPI_Comm_set_errhandler", RECORDER_MPI_DECL(PMPI_Comm_set_errhandler), &RECORDER_WRAPPEE_HANDLE(PMPI_Comm_set_errhandler) },
    { "PMPI_Barrier", RECORDER_MPI_DECL(PMPI_Barrier), &RECORDER_WRAPPEE_HANDLE(PMPI_Barrier) },
    { "PMPI_Bcast", RECORDER_MPI_DECL(PMPI_Bcast), &RECORDER_WRAPPEE_HANDLE(PMPI_Bcast) },
    { "PMPI_Gather", RECORDER_MPI_DECL(PMPI_Gather), &RECORDER_WRAPPEE_HANDLE(PMPI_Gather) },
    { "PMPI_Gatherv", RECORDER_MPI_DECL(PMPI_Gatherv), &RECORDER_WRAPPEE_HANDLE(PMPI_Gatherv) },
    { "PMPI_Scatter", RECORDER_MPI_DECL(PMPI_Scatter), &RECORDER_WRAPPEE_HANDLE(PMPI_Scatter) },
    { "PMPI_Scatterv", RECORDER_MPI_DECL(PMPI_Scatterv), &RECORDER_WRAPPEE_HANDLE(PMPI_Scatterv) },
    { "PMPI_Allgather", RECORDER_MPI_DECL(PMPI_Allgather), &RECORDER_WRAPPEE_HANDLE(PMPI_Allgather) },
    { "PMPI_Allgatherv", RECORDER_MPI_DECL(PMPI_Allgatherv), &RECORDER_WRAPPEE_HANDLE(PMPI_Allgatherv) },
    { "PMPI_Alltoall", RECORDER_MPI_DECL(PMPI_Alltoall), &RECORDER_WRAPPEE_HANDLE(PMPI_Alltoall) },
    { "PMPI_Reduce", RECORDER_MPI_DECL(PMPI_Reduce), &RECORDER_WRAPPEE_HANDLE(PMPI_Reduce) },
    { "PMPI_Allreduce", RECORDER_MPI_DECL(PMPI_Allreduce), &RECORDER_WRAPPEE_HANDLE(PMPI_Allreduce) },
    { "PMPI_Reduce_scatter", RECORDER_MPI_DECL(PMPI_Reduce_scatter), &RECORDER_WRAPPEE_HANDLE(PMPI_Reduce_scatter) },
    { "PMPI_Scan", RECORDER_MPI_DECL(PMPI_Scan), &RECORDER_WRAPPEE_HANDLE(PMPI_Scan) },
    { "PMPI_Type_commit", RECORDER_MPI_DECL(PMPI_Type_commit), &RECORDER_WRAPPEE_HANDLE(PMPI_Type_commit) },
    { "PMPI_Type_contiguous", RECORDER_MPI_DECL(PMPI_Type_contiguous), &RECORDER_WRAPPEE_HANDLE(PMPI_Type_contiguous) },
    { "PMPI_Type_extent", RECORDER_MPI_DECL(PMPI_Type_extent), &RECORDER_WRAPPEE_HANDLE(PMPI_Type_extent) },
    { "PMPI_Type_free", RECORDER_MPI_DECL(PMPI_Type_free), &RECORDER_WRAPPEE_HANDLE(PMPI_Type_free) },
    { "PMPI_Type_hindexed", RECORDER_MPI_DECL(PMPI_Type_hindexed), &RECORDER_WRAPPEE_HANDLE(PMPI_Type_hindexed) },
    { "PMPI_Op_create", RECORDER_MPI_DECL(PMPI_Op_create), &RECORDER_WRAPPEE_HANDLE(PMPI_Op_create) },
    { "PMPI_Op_free", RECORDER_MPI_DECL(PMPI_Op_free), &RECORDER_WRAPPEE_HANDLE(PMPI_Op_free) },
    { "PMPI_Type_get_envelope", RECORDER_MPI_DECL(PMPI_Type_get_envelope), &RECORDER_WRAPPEE_HANDLE(PMPI_Type_get_envelope) },
    { "PMPI_Type_size", RECORDER_MPI_DECL(PMPI_Type_size), &RECORDER_WRAPPEE_HANDLE(PMPI_Type_size) },
    { "PMPI_Type_create_darray", RECORDER_MPI_DECL(PMPI_Type_create_darray), &RECORDER_WRAPPEE_HANDLE(PMPI_Type_create_darray) },
    { "PMPI_File_get_size", RECORDER_MPI_DECL(PMPI_File_get_size), &RECORDER_WRAPPEE_HANDLE(PMPI_File_get_size) },
    { "PMPI_Cart_rank", RECORDER_MPI_DECL(PMPI_Cart_rank), &RECORDER_WRAPPEE_HANDLE(PMPI_Cart_rank) },
    { "PMPI_Cart_create", RECORDER_MPI_DECL(PMPI_Cart_create), &RECORDER_WRAPPEE_HANDLE(PMPI_Cart_create) },
    { "PMPI_Cart_get", RECORDER_MPI_DECL(PMPI_Cart_get), &RECORDER_WRAPPEE_HANDLE(PMPI_Cart_get) },
    { "PMPI_Cart_shift", RECORDER_MPI_DECL(PMPI_Cart_shift), &RECORDER_WRAPPEE_HANDLE(PMPI_Cart_shift) },
    { "PMPI_Wait", RECORDER_MPI_DECL(PMPI_Wait), &RECORDER_WRAPPEE_HANDLE(PMPI_Wait) },
    { "PMPI_Send", RECORDER_MPI_DECL(PMPI_Send), &RECORDER_WRAPPEE_HANDLE(PMPI_Send) },
    { "PMPI_Recv", RECORDER_MPI_DECL(PMPI_Recv), &RECORDER_WRAPPEE_HANDLE(PMPI_Recv) },
    { "PMPI_Sendrecv", RECORDER_MPI_DECL(PMPI_Sendrecv), &RECORDER_WRAPPEE_HANDLE(PMPI_Sendrecv) },
    { "PMPI_Isend", RECORDER_MPI_DECL(PMPI_Isend), &RECORDER_WRAPPEE_HANDLE(PMPI_Isend) },
    { "PMPI_Irecv", RECORDER_MPI_DECL(PMPI_Irecv), &RECORDER_WRAPPEE_HANDLE(PMPI_Irecv) },
    { "PMPI_Info_create", RECORDER_MPI_DECL(PMPI_Info_create), &RECORDER_WRAPPEE_HANDLE(PMPI_Info_create) },
    { "PMPI_Info_set", RECORDER_MPI_DECL(PMPI_Info_set), &RECORDER_WRAPPEE_HANDLE(PMPI_Info_set) },
    { "PMPI_Info_get", RECORDER_MPI_DECL(PMPI_Info_get), &RECORDER_WRAPPEE_HANDLE(PMPI_Info_get) },
    { "PMPI_Waitall", RECORDER_MPI_DECL(PMPI_Waitall), &RECORDER_WRAPPEE_HANDLE(PMPI_Waitall) },
    { "PMPI_Waitsome", RECORDER_MPI_DECL(PMPI_Waitsome), &RECORDER_WRAPPEE_HANDLE(PMPI_Waitsome) },
    { "PMPI_Waitany", RECORDER_MPI_DECL(PMPI_Waitany), &RECORDER_WRAPPEE_HANDLE(PMPI_Waitany) },
    { "PMPI_Ssend", RECORDER_MPI_DECL(PMPI_Ssend), &RECORDER_WRAPPEE_HANDLE(PMPI_Ssend) },
    { "PMPI_Comm_split", RECORDER_MPI_DECL(PMPI_Comm_split), &RECORDER_WRAPPEE_HANDLE(PMPI_Comm_split) },
    { "PMPI_Comm_dup", RECORDER_MPI_DECL(PMPI_Comm_dup), &RECORDER_WRAPPEE_HANDLE(PMPI_Comm_dup) },
    { "PMPI_Comm_create", RECORDER_MPI_DECL(PMPI_Comm_create), &RECORDER_WRAPPEE_HANDLE(PMPI_Comm_create) },
    { "PMPI_File_seek", RECORDER_MPI_DECL(PMPI_File_seek), &RECORDER_WRAPPEE_HANDLE(PMPI_File_seek) },
    { "PMPI_File_seek_shared", RECORDER_MPI_DECL(PMPI_File_seek_shared), &RECORDER_WRAPPEE_HANDLE(PMPI_File_seek_shared) },
    { "PMPI_Ibcast", RECORDER_MPI_DECL(PMPI_Ibcast), &RECORDER_WRAPPEE_HANDLE(PMPI_Ibcast) },
    { "PMPI_Test", RECORDER_MPI_DECL(PMPI_Test), &RECORDER_WRAPPEE_HANDLE(PMPI_Test) },
    { "PMPI_Testall", RECORDER_MPI_DECL(PMPI_Testall), &RECORDER_WRAPPEE_HANDLE(PMPI_Testall) },
    { "PMPI_Testsome", RECORDER_MPI_DECL(PMPI_Testsome), &RECORDER_WRAPPEE_HANDLE(PMPI_Testsome) },
    { "PMPI_Testany", RECORDER_MPI_DECL(PMPI_Testany), &RECORDER_WRAPPEE_HANDLE(PMPI_Testany) },
    { "PMPI_Ireduce", RECORDER_MPI_DECL(PMPI_Ireduce), &RECORDER_WRAPPEE_HANDLE(PMPI_Ireduce) },
    { "PMPI_Igather", RECORDER_MPI_DECL(PMPI_Igather), &RECORDER_WRAPPEE_HANDLE(PMPI_Igather) },
    { "PMPI_Iscatter", RECORDER_MPI_DECL(PMPI_Iscatter), &RECORDER_WRAPPEE_HANDLE(PMPI_Iscatter) },
    { "PMPI_Ialltoall", RECORDER_MPI_DECL(PMPI_Ialltoall), &RECORDER_WRAPPEE_HANDLE(PMPI_Ialltoall) },
    { "PMPI_Comm_free", RECORDER_MPI_DECL(PMPI_Comm_free), &RECORDER_WRAPPEE_HANDLE(PMPI_Comm_free) },
    { "PMPI_Cart_sub", RECORDER_MPI_DECL(PMPI_Cart_sub), &RECORDER_WRAPPEE_HANDLE(PMPI_Cart_sub) },
    { "PMPI_Comm_split_type", RECORDER_MPI_DECL(PMPI_Comm_split_type), &RECORDER_WRAPPEE_HANDLE(PMPI_Comm_split_type) },

    /* HDF5 Function Calls */
    /* NOTE: using HDF5 1.8 version */
    { "H5Fcreate", RECORDER_HDF5_DECL(H5Fcreate), &RECORDER_WRAPPEE_HANDLE(H5Fcreate) },
    { "H5Fopen", RECORDER_HDF5_DECL(H5Fopen), &RECORDER_WRAPPEE_HANDLE(H5Fopen) },
    { "H5Fclose", RECORDER_HDF5_DECL(H5Fclose), &RECORDER_WRAPPEE_HANDLE(H5Fclose) },
    { "H5Fflush", RECORDER_HDF5_DECL(H5Fflush), &RECORDER_WRAPPEE_HANDLE(H5Fflush) },
    { "H5Gclose", RECORDER_HDF5_DECL(H5Gclose), &RECORDER_WRAPPEE_HANDLE(H5Gclose) },
    { "H5Gcreate1", RECORDER_HDF5_DECL(H5Gcreate1), &RECORDER_WRAPPEE_HANDLE(H5Gcreate1) },
    { "H5Gcreate2", RECORDER_HDF5_DECL(H5Gcreate2), &RECORDER_WRAPPEE_HANDLE(H5Gcreate2) },
    { "H5Gget_objinfo", RECORDER_HDF5_DECL(H5Gget_objinfo), &RECORDER_WRAPPEE_HANDLE(H5Gget_objinfo) },
    { "H5Giterate", RECORDER_HDF5_DECL(H5Giterate), &RECORDER_WRAPPEE_HANDLE(H5Giterate) },
    { "H5Gopen1", RECORDER_HDF5_DECL(H5Gopen1), &RECORDER_WRAPPEE_HANDLE(H5Gopen1) },
    { "H5Gopen2", RECORDER_HDF5_DECL(H5Gopen2), &RECORDER_WRAPPEE_HANDLE(H5Gopen2) },
    { "H5Dclose", RECORDER_HDF5_DECL(H5Dclose), &RECORDER_WRAPPEE_HANDLE(H5Dclose) },
    { "H5Dcreate1", RECORDER_HDF5_DECL(H5Dcreate1), &RECORDER_WRAPPEE_HANDLE(H5Dcreate1) },
    { "H5Dcreate2", RECORDER_HDF5_DECL(H5Dcreate2), &RECORDER_WRAPPEE_HANDLE(H5Dcreate2) },
    { "H5Dget_create_plist", RECORDER_HDF5_DECL(H5Dget_create_plist), &RECORDER_WRAPPEE_HANDLE(H5Dget_create_plist) },
    { "H5Dget_space", RECORDER_HDF5_DECL(H5Dget_space), &RECORDER_WRAPPEE_HANDLE(H5Dget_space) },
    { "H5Dget_type", RECORDER_HDF5_DECL(H5Dget_type), &RECORDER_WRAPPEE_HANDLE(H5Dget_type) },
    { "H5Dopen1", RECORDER_HDF5_DECL(H5Dopen1), &RECORDER_WRAPPEE_HANDLE(H5Dopen1) },
    { "H5Dopen2", RECORDER_HDF5_DECL(H5Dopen2), &RECORDER_WRAPPEE_HANDLE(H5Dopen2) },
    { "H5Dread", RECORDER_HDF5_DECL(H5Dread), &RECORDER_WRAPPEE_HANDLE(H5Dread) },
    { "H5Dwrite", RECORDER_HDF5_DECL(H5Dwrite), &RECORDER_WRAPPEE_HANDLE(H5Dwrite) },
    { "H5Dset_extent", RECORDER_HDF5_DECL(H5Dset_extent), &RECORDER_WRAPPEE_HANDLE(H5Dset_extent) },
    { "H5Sclose", RECORDER_HDF5_DECL(H5Sclose), &RECORDER_WRAPPEE_HANDLE(H5Sclose) },
    { "H5Screate", RECORDER_HDF5_DECL(H5Screate), &RECORDER_WRAPPEE_HANDLE(H5Screate) },
    { "H5Screate_simple", RECORDER_HDF5_DECL(H5Screate_simple), &RECORDER_WRAPPEE_HANDLE(H5Screate_simple) },
    { "H5Sget_select_npoints", RECORDER_HDF5_DECL(H5Sget_select_npoints), &RECORDER_WRAPPEE_HANDLE(H5Sget_select_npoints) },
    { "H5Sget_simple_extent_dims", RECORDER_HDF5_DECL(H5Sget_simple_extent_dims), &RECORDER_WRAPPEE_HANDLE(H5Sget_simple_extent_dims) },
    { "H5Sget_simple_extent_npoints", RECORDER_HDF5_DECL(H5Sget_simple_extent_npoints), &RECORDER_WRAPPEE_HANDLE(aaaaaaaaaa) },
    { "H5Sselect_elements", RECORDER_HDF5_DECL(H5Sselect_elements), &RECORDER_WRAPPEE_HANDLE(H5Sselect_elements) },
    { "H5Sselect_hyperslab", RECORDER_HDF5_DECL(H5Sselect_hyperslab), &RECORDER_WRAPPEE_HANDLE(H5Sselect_hyperslab) },
    { "H5Sselect_none", RECORDER_HDF5_DECL(H5Sselect_none), &RECORDER_WRAPPEE_HANDLE(H5Sselect_none) },
    { "H5Tclose", RECORDER_HDF5_DECL(H5Tclose), &RECORDER_WRAPPEE_HANDLE(H5Tclose) },
    { "H5Tcopy", RECORDER_HDF5_DECL(H5Tcopy), &RECORDER_WRAPPEE_HANDLE(H5Tcopy) },
    { "H5Tget_class", RECORDER_HDF5_DECL(H5Tget_class), &RECORDER_WRAPPEE_HANDLE(H5Tget_class) },
    { "H5Tget_size", RECORDER_HDF5_DECL(H5Tget_size), &RECORDER_WRAPPEE_HANDLE(H5Tget_size) },
    { "H5Tset_size", RECORDER_HDF5_DECL(H5Tset_size), &RECORDER_WRAPPEE_HANDLE(H5Tset_size) },
    { "H5Tcreate", RECORDER_HDF5_DECL(H5Tcreate), &RECORDER_WRAPPEE_HANDLE(H5Tcreate) },
    { "H5Tinsert", RECORDER_HDF5_DECL(H5Tinsert), &RECORDER_WRAPPEE_HANDLE(H5Tinsert) },
    { "H5Aclose", RECORDER_HDF5_DECL(H5Aclose), &RECORDER_WRAPPEE_HANDLE(H5Aclose) },
    { "H5Acreate1", RECORDER_HDF5_DECL(H5Acreate1), &RECORDER_WRAPPEE_HANDLE(H5Acreate1) },
    { "H5Acreate2", RECORDER_HDF5_DECL(H5Acreate2), &RECORDER_WRAPPEE_HANDLE(H5Acreate2) },
    { "H5Aget_name", RECORDER_HDF5_DECL(H5Aget_name), &RECORDER_WRAPPEE_HANDLE(H5Aget_name) },
    { "H5Aget_num_attrs", RECORDER_HDF5_DECL(H5Aget_num_attrs), &RECORDER_WRAPPEE_HANDLE(H5Aget_num_attrs) },
    { "H5Aget_space", RECORDER_HDF5_DECL(H5Aget_space), &RECORDER_WRAPPEE_HANDLE(H5Aget_space) },
    { "H5Aget_type", RECORDER_HDF5_DECL(H5Aget_type), &RECORDER_WRAPPEE_HANDLE(H5Aget_type) },
    { "H5Aopen", RECORDER_HDF5_DECL(H5Aopen), &RECORDER_WRAPPEE_HANDLE(H5Aopen) },
    { "H5Aopen_idx", RECORDER_HDF5_DECL(H5Aopen_idx), &RECORDER_WRAPPEE_HANDLE(H5Aopen_idx) },
    { "H5Aopen_name", RECORDER_HDF5_DECL(H5Aopen_name), &RECORDER_WRAPPEE_HANDLE(H5Aopen_name) },
    { "H5Aread", RECORDER_HDF5_DECL(H5Aread), &RECORDER_WRAPPEE_HANDLE(H5Aread) },
    { "H5Awrite", RECORDER_HDF5_DECL(H5Awrite), &RECORDER_WRAPPEE_HANDLE(H5Awrite) },
    { "H5Pclose", RECORDER_HDF5_DECL(H5Pclose), &RECORDER_WRAPPEE_HANDLE(H5Pclose) },
    { "H5Pcreate", RECORDER_HDF5_DECL(H5Pcreate), &RECORDER_WRAPPEE_HANDLE(H5Pcreate) },
    { "H5Pget_chunk", RECORDER_HDF5_DECL(H5Pget_chunk), &RECORDER_WRAPPEE_HANDLE(H5Pget_chunk) },
    { "H5Pget_mdc_config", RECORDER_HDF5_DECL(H5Pget_mdc_config), &RECORDER_WRAPPEE_HANDLE(H5Pget_mdc_config) },
    { "H5Pset_alignment", RECORDER_HDF5_DECL(H5Pset_alignment), &RECORDER_WRAPPEE_HANDLE(H5Pset_alignment) },
    { "H5Pset_chunk", RECORDER_HDF5_DECL(H5Pset_chunk), &RECORDER_WRAPPEE_HANDLE(H5Pset_chunk) },
    { "H5Pset_dxpl_mpio", RECORDER_HDF5_DECL(H5Pset_dxpl_mpio), &RECORDER_WRAPPEE_HANDLE(H5Pset_dxpl_mpio) },
    { "H5Pset_fapl_core", RECORDER_HDF5_DECL(H5Pset_fapl_core), &RECORDER_WRAPPEE_HANDLE(H5Pset_fapl_core) },
    { "H5Pset_fapl_mpio", RECORDER_HDF5_DECL(H5Pset_fapl_mpio), &RECORDER_WRAPPEE_HANDLE(H5Pset_fapl_mpio) },
    { "H5Pset_fapl_mpiposix", RECORDER_HDF5_DECL(H5Pset_fapl_mpiposix), &RECORDER_WRAPPEE_HANDLE(H5Pset_fapl_mpiposix) },
    { "H5Pset_istore_k", RECORDER_HDF5_DECL(H5Pset_istore_k), &RECORDER_WRAPPEE_HANDLE(H5Pset_istore_k) },
    { "H5Pset_mdc_config", RECORDER_HDF5_DECL(H5Pset_mdc_config), &RECORDER_WRAPPEE_HANDLE(H5Pset_mdc_config) },
    { "H5Pset_meta_block_size", RECORDER_HDF5_DECL(H5Pset_meta_block_size), &RECORDER_WRAPPEE_HANDLE(H5Pset_meta_block_size) },
    { "H5Lexists", RECORDER_HDF5_DECL(H5Lexists), &RECORDER_WRAPPEE_HANDLE(H5Lexists) },
    { "H5Lget_val", RECORDER_HDF5_DECL(H5Lget_val), &RECORDER_WRAPPEE_HANDLE(H5Lget_val) },
    { "H5Literate", RECORDER_HDF5_DECL(H5Literate), &RECORDER_WRAPPEE_HANDLE(H5Literate) },
    { "H5Literate1", RECORDER_HDF5_DECL(H5Literate1), &RECORDER_WRAPPEE_HANDLE(H5Literate1) },
    { "H5Literate2", RECORDER_HDF5_DECL(H5Literate2), &RECORDER_WRAPPEE_HANDLE(H5Literate2) },
    { "H5Oclose", RECORDER_HDF5_DECL(H5Oclose), &RECORDER_WRAPPEE_HANDLE(H5Oclose) },
    { "H5Oget_info", RECORDER_HDF5_DECL(H5Oget_info), &RECORDER_WRAPPEE_HANDLE(H5Oget_info) },
    { "H5Oget_info_by_name", RECORDER_HDF5_DECL(H5Oget_info_by_name), &RECORDER_WRAPPEE_HANDLE(H5Oget_info_by_name) },
    { "H5Oopen", RECORDER_HDF5_DECL(H5Oopen), &RECORDER_WRAPPEE_HANDLE(H5Oopen) },
    { "H5Pset_coll_metadata_write", RECORDER_HDF5_DECL(H5Pset_coll_metadata_write), &RECORDER_WRAPPEE_HANDLE(H5Pset_coll_metadata_write) },
    { "H5Pget_coll_metadata_write", RECORDER_HDF5_DECL(H5Pget_coll_metadata_write), &RECORDER_WRAPPEE_HANDLE(H5Pget_coll_metadata_write) },
    { "H5Pset_all_coll_metadata_ops", RECORDER_HDF5_DECL(H5Pset_all_coll_metadata_ops), &RECORDER_WRAPPEE_HANDLE(H5Pset_all_coll_metadata_ops) },
    { "H5Pget_all_coll_metadata_ops", RECORDER_HDF5_DECL(H5Pget_all_coll_metadata_ops), &RECORDER_WRAPPEE_HANDLE(H5Pget_all_coll_metadata_ops) },

};

#define GOTCHA_NFUNCS (sizeof(recorder_wrappers) / sizeof(gotcha_binding_t))

int setup_gotcha_wrappers(void)
{
    /* insert our I/O wrappers using gotcha */
    enum gotcha_error_t result;
    result = gotcha_wrap(recorder_wrappers, GOTCHA_NFUNCS, "recorder");
    if (result != GOTCHA_SUCCESS) {
        LOGERR("gotcha_wrap() returned %d", (int) result);
        if (result == GOTCHA_FUNCTION_NOT_FOUND) {
            /* one or more functions were not found */
            void* fn;
            gotcha_wrappee_handle_t* hdlptr;
            for (int i = 0; i < GOTCHA_NFUNCS; i++) {
                hdlptr = recorder_wrappers[i].function_handle;
                fn = gotcha_get_wrappee(*hdlptr);
                if (NULL == fn) {
                    LOGWARN("Gotcha failed to wrap function '%s'",
                            recorder_wrappers[i].name);
                }
            }
        } else {
            return -1;
        }
    }
    return 0;
}
//#endif